# Generated by Django 5.0.3 on 2024-11-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('availability', models.CharField(max_length=255)),
            ],
        ),
    ]
