# Generated by Django 4.2.16 on 2024-11-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0002_furniture_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniture',
            old_name='type',
            new_name='category',
        ),
    ]
